mysite/myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'

urlpatterns = [
    path('base/', views.base, name = 'base'),
    path('user_info/', views.user_info, name = 'user_info'),
    path("just_form/", views.just_form, name = "just_form"),
    path('<int:id>/data', views.data, name='data')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('', views.home, name='home'),
    path("admin/", admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

mysite/myapp/models.py
from django.db import models

# Create your models here.

#one to many relationship
class Person(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Car(models.Model):
    model = models.CharField(max_length=200)
    number = models.PositiveIntegerField()
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return self.model

mysite/myapp/views.py
from .models import Car
from django.shortcuts import render, redirect
from django.urls import reverse
# Create your views here.

from django.http import HttpResponse

def home(request):
    return render(request, 'home.html') 
    


def base(request):
    title  = "THE BASE PAGE"
    cars_list = Car.objects.all()

    return render(request, "myapp/main.html", {'title': title, "cars_list": cars_list })

def user_info(request):

    if request.method == 'GET':
        
        # print("request.GET ==>>", request.GET)
        print("request.GET==>>", request.session.get('username', False))

        if request.session.get('username', False):
            userinfo = {
                'username': request.session['username'],
                'country': request.session['country']
            }

        else:
            userinfo = False

        context = {'userinfo': userinfo,
                    'title': 'User Info Page'}
        template = 'myapp/user_info.html'
        return render(request, template, context)
    
    elif request.method == "POST":
        return HttpResponse('POST request here')

def just_form(request):
    if request.method == "GET":
        context = {'title': 'Form Page'}
        template = 'myapp/just_form.html'
        return render(request, template, context)

    elif request.method == "POST":
        print("request.POST==>>", request.POST)
        username = request.POST.get('username')
        country = request.POST.get('country')
        request.session['username'] = username
        request.session['country'] = country

        return redirect(reverse('myapp:user_info'))


def data(request, id):
    car = Car.objects.get(id=id)
    context = {'car': car}
    return render(request, 'myapp/data.html', context)

mysite/myapp/templates/myapp/data.html
{% extends 'base.html' %}
{% block content %}
<h1>Car details:</h1>
<br>
<table class="table" style="width: 30%">
    <thead>
        <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="row">Model:</td>
            <td class="text-dark">{{car.model}}</td>
        </tr>
        <tr>
            <td scope="row">Number:</td>
            <td>{{car.number}}</td>
        </tr>
        <tr>
            <td>Owner:</td>
            <td>{{car.owner}}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

mysite/myapp/templates/myapp/just_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid d-flex justify-content-center">
    <form method="POST" action="" sytle="width: 40%;">

        <!-- ADD THIS TAG IN HTML FORMS WITH POST REQUESTS-->
        {% csrf_token %}
        
        <div class="form-group">
            <label for="exampleInputEmail1">Enter Name</label>
            <input name="username" type="text" class="form-control my-2" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Enter Country</label>
            <input name="country" type="text" class="form-control my-2" id="exampleInputPassword1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>
</div>

{% endblock  %}

mysite/myapp/templates/myapp/main.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the films MAIN page</h1>
<br>
<h4>Films saved in our database:</h4>
<ul>
    {% for car in cars_list %}

    <li>Model: {{car.model}}, Number: {{car.number}}, Owner: "{{car.owner}}"</li>
    {% endfor %}
</ul>
{% endblock %}

mysite/myapp/templates/myapp/user_info.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the myapp USER_INFO page</h1>
<br>
{% if userinfo %}
  <h4>username: {{userinfo.username}}</h4>
  <h4>country: {{userinfo.country}}</h4>
{% else %}
  <h4>username: not informed</h4>
  <h4>country: not informed</h4>
{% endif %}
{% endblock  %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
    <title>My App</title>
    {% endif %}

</head>

<body>
    <!-- BOOTSTRAP NAVBAR CODE -->
    <nav class="navbar navbar-expand-lg navbar-blue bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 90%;">
            <span class="navbar-text text-white">FIRST DJANGO APP</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'myapp:base' %}">BASE</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'myapp:user_info' %}">UserInfo</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'myapp:just_form' %}">UserForm</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- END OF NAVBAR CODE-->


    <div class="container-fluid mt-5" style="max-width: 80%">
        <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

mysite/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the Home Page</h1>
<br>
<h3>Thanks for visiting us</h3>
<br>
<p>MVT means:</p>
<ul>
  <li>Model</li>
  <li>View</li>
  <li>Template</li>
</ul>
{% endblock  %}